# Nom de l'environnement Conda
name: llm-dev

# Canaux priorisés pour la recherche des paquets
channels:
  - pytorch
  - nvidia
  - conda-forge
  - anaconda

dependencies:
  # --- 1. Dépendances de base installées via Conda ---
  # Stables et gèrent les dépendances complexes (C++, etc.)
  - python=3.10
  - pip
  - cudatoolkit # Ajouté pour une meilleure résolution des dépendances CUDA par Conda
  - scikit-learn # Souvent requis par d'autres bibliothèques
  - tqdm # Utile pour les barres de progression

  # --- 2. PyTorch depuis son canal dédié pour la meilleure compatibilité CUDA ---
  - pytorch::pytorch=2.3.0
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.1

  # --- 3. Paquets Python installés via Pip ---
  # Pip s'exécute après que Conda ait préparé l'environnement de base.
  - pip:
    # Pile principale de Hugging Face pour le Fine-Tuning
    # Ces versions sont récentes et compatibles entre elles
    - transformers>=4.51.0
    - accelerate==0.30.1
    - datasets==2.19.1
    - peft==0.10.0
    - trl==0.8.6
    - bitsandbytes==0.43.1 # Pour la quantification QLoRA

    # Cadres RAG & Bases de données vectorielles
    - faiss-gpu-cu12 # SPÉCIFIQUE pour CUDA 12.x, plus fiable que la version Conda
    - langchain==0.1.20
    - llama-index==0.10.41
    - llama-index-llms-huggingface
    - llama-index-embeddings-huggingface

    # Manipulation de PDF & Données
    - pymupdf==1.24.4
    - sentence-transformers>=2.7.0

    # Utilitaires & Dépendances
    - protobuf
    - sentencepiece
    - huggingface_hub[hf_xet]
    - ipykernel # Indispensable pour utiliser l'environnement dans Jupyter
