name: llm-dev
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  # 1. Core Conda packages
  - python=3.10
  - pip
  - faiss-gpu

  # 2. PyTorch from its dedicated channel
  #    This automatically pulls the correct CUDA toolkit.
  - pytorch::pytorch=2.3.0
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.1

  # 3. Jupyter and Widgets for a better interactive experience
  - jupyterlab
  - ipywidgets

  # 4. All other Python packages installed via Pip
  - pip:
    # Core Hugging Face Stack for Fine-Tuning
    - transformers==4.41.2
    - accelerate==0.30.1
    - datasets==2.19.1
    - peft==0.10.0
    - trl==0.8.6
    - bitsandbytes==0.43.1

    # RAG Frameworks & Vector DBs
    - langchain==0.1.20
    - llama-index==0.10.41
    - llama-index-llms-huggingface
    - llama-index-embeddings-huggingface

    # PDF & Data Handling
    - pymupdf==1.24.4
    - sentence-transformers==2.7.0

    # Utilities & Dependencies
    - protobuf
    - sentencepiece
    - huggingface_hub[hf_xet]
